enc:
  required: True
  type: dict
  schema:
    # set True if you want to display whole uploaded map
    autosize:
      required: False
      type: boolean

    # size of displayed map
    size:
      required: True
      type: list
      maxlength: 2
      schema:
        type: float
        min: 1.0

    # that's where you want bottom-left corner to be
    origin:
      required: True
      excludes: center
      type: list
      maxlength: 2
      schema:
        type: float

    # that's where you want the center of a map to be
    center:
      required: True
      excludes: origin
      type: list
      maxlength: 2
      schema:
        type: float

    # UTM zone required for coordinates to work correctly
    crs:
      required: True
      type: string

    # depths are required for both formats, if not set they will be assigned default values
    depths:
      required: False
      type: list
      minlength: 1
      schema:
        type: integer
        min: 0

    # you can pick specific S-57 layers you want to extract
    # WARNING: LNDARE, COALNE and DEPARE are loaded on default as Land, Shore and Bathymetry
    S57_layers:
      required: False
      type: dict
      minlength: 0
      valuesrules:
        type: string
      keysrules:
        type: string

    # you must put paths to some resources
    resources:
      required: True
      type: list
      minlength: 1
      schema:
        type: string

    weather:
      required: False
      type: dict
      schema:
        PyThor_address:
          required: False
          type: string
        variables:
          type: list
          required: False
          schema:
            type: string
            allowed:
              - wave_direction
              - wave_height
              - wave_period
              - wind_direction
              - wind_speed
              - sea_current_speed
              - sea_current_direction
              - tide_height
    time:
      required: False
      type: dict
      schema:
        time_start:
          required: True
          type: string
          regex: "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-[0-9]{4} [0-2][0-9]:[0-5][0-9]$"  # dd-mm-yyyy hh:mm
        time_end:
          required: True
          type: string
          regex: "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-[0-9]{4} [0-2][0-9]:[0-5][0-9]$"  # dd-mm-yyyy hh:mm
        period:
          required: True
          type: string
          allowed:
            - hour
            - day
            - week
            - month
            - year
        period_multiplier:
          required: True
          type: float


display:
  required: False
  type: dict
  schema:
    colorbar:
      required: False
      type: boolean

    dark_mode:
      required: False
      type: boolean

    fullscreen:
      required: False
      type: boolean

    resolution:
      required: False
      type: integer

    anchor:
      required: False
      type: string

    dpi:
      required: False
      type: integer

    controls:
      required: False
      type: boolean
